moscow:
  title: 'Moscow'
  title_ru: 'Москва'
  title_in: 'в Москве'
  address: ['Духовской переулок', 'дом 17', 'строение 15']
  phone: '+7 926 042-58-85'
  yclients: '95580'
  video: 'fgeYJU9x8wY'
  old_key: msk

nizhny:
  title: 'Nizhny'
  title_ru: 'Нижний Новгород'
  title_in: 'в Нижнем Новгороде'
  address: ['улица Новая', 'дом 28', '1 подъезд', '5 этаж']
  phone: '+7 920 111-56-88'
  yclients: '58259'
  video: 'qkuyIJWJbk0'
  old_key: nn
