moscow:
  title: 'Moscow'
  title_ru: 'Москва'
  title_in: 'в Москве'
  address: ['Духовской переулок', 'дом 17', 'строение 15']
  phone: '+7 926 042-58-85'
  yclients: '95580'
  video: 'fgeYJU9x8wY'
  old_key: msk
  ymap: 'constructor%3Ad80183db04db64e3a7bc6521e6cdd0c65b4e2869c29b6bc8aa1d2f2c92a4feed'

nizhny:
  title: 'Nizhny'
  title_ru: 'Нижний Новгород'
  title_in: 'в Нижнем Новгороде'
  address: ['улица Варварская', 'дом 32', '4 этаж']
  phone: '+7 920 111-56-88'
  yclients: '58259'
  video: 'qkuyIJWJbk0'
  old_key: nn
  ymap: 'constructor%3Ad18e90c9828d604b3cc11fe348fc0f0372dc3c24c105d7327afa877e3df121c7'
