left:
  Маникюр + покрытие Luxio : 1300
  Маникюр + покрытие Luxio + укрепление Luxio Build: 1500
  Маникюр + покрытие Luxio + френч: 1500
  Маникюр + покрытие Luxio + лунки: 1700
  Маникюр + покрытие Luxio + лунки + френч: 1800
  Покрытие Luxio: 1100
  Покрытие Luxio + укрепление Luxio Build: 1300
  Маникюр без покрытия:
    - 800
    - …маникюр обрезной, аппаратный или комбинированный по желанию гостьи

right:
  Педикюр + покрытие Luxio без шлифовки стоп: 1400
  Педикюр средствами Clearance + покрытие Luxio: 2500
  Педикюр средствами Clearance без покрытия: 2000
  Педикюр без покрытия и шлифовки стоп: 1000
  Снятие покрытия:
    - 200
    -
    - true

  Дизайн 1 ноготь: 100
  Лечение системой IBX: 450
  Архитектура бровей:
    - 1100
    - моделирование формы, окрашивание стойким красителем и коррекция
    - true